/*
 Generated by typeshare 1.13.4
*/

export interface SshConfig {
	host: string;
	port: string;
	username: string;
	password: string;
}

export interface HugoConfig {
	url: string;
	hugo_cmd_path: string;
	base_path: string;
	content_path: string;
	image_path: string;
	hidden_path: string;
}

export interface CmsConfig {
	hugo_config: HugoConfig;
}

/**
 * 프론트엔드와 통신하는 통합 설정 구조체
 * 실제 저장은 ClientConfig(로컬)와 ServerConfig(서버)로 분리됨
 */
export interface AppConfig {
	ssh_config: SshConfig;
	cms_config: CmsConfig;
}

export enum NodeType {
	File = "File",
	Directory = "Directory",
}

export interface FileSystemNode {
	name: string;
	type_: NodeType;
	is_hidden: boolean;
	children: FileSystemNode[];
}

export interface InputField {
	name: string;
	type: string;
	label: string;
	default?: string;
}

export type Trigger = 
	| { type: "manual", content: {
	label: string;
	input: InputField[];
}}
	| { type: "hook", content: {
	event: HookEvent;
}}
	| { type: "cron", content: {
	schedule: string;
	label: string;
}};

/** 서버의 plugin.json 파싱 결과 */
export interface PluginManifest {
	name: string;
	description: string;
	version: string;
	entry: string;
	triggers: Trigger[];
}

export type PluginAction = 
	| { type: "refresh_tree", content?: undefined }
	| { type: "toast", content: {
	message: string;
	toast_type: string;
}}
	| { type: "open_file", content: {
	path: string;
}};

/** 스크립트 stdout JSON 파싱 결과 */
export interface PluginResult {
	success: boolean;
	message?: string;
	error?: string;
	actions?: PluginAction[];
}

export interface PrerequisiteResult {
	curl: boolean;
	tar: boolean;
	git: boolean;
}

export enum HookEvent {
	AfterFileMove = "AfterFileMove",
	AfterFileSave = "AfterFileSave",
	AfterFileDelete = "AfterFileDelete",
	AfterFileCreate = "AfterFileCreate",
}

