/*
 Generated by typeshare 1.13.4
*/

export interface SshConfig {
	host: string;
	port: string;
	username: string;
	password: string;
}

export interface HugoConfig {
	url: string;
	hugo_cmd_path: string;
	base_path: string;
	content_path: string;
	image_path: string;
	hidden_path: string;
}

export interface CmsConfig {
	hugo_config: HugoConfig;
}

/**
 * 프론트엔드와 통신하는 통합 설정 구조체
 * 실제 저장은 ClientConfig(로컬)와 ServerConfig(서버)로 분리됨
 */
export interface AppConfig {
	ssh_config: SshConfig;
	cms_config: CmsConfig;
}

export enum NodeType {
	File = "File",
	Directory = "Directory",
}

export interface FileSystemNode {
	name: string;
	type_: NodeType;
	is_hidden: boolean;
	children: FileSystemNode[];
}

export interface PrerequisiteResult {
	curl: boolean;
	tar: boolean;
	git: boolean;
}

